language: node_js
node_js:
- 4.4.2
- 5.10.1
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- $CI_ACTION
env:
  global:
  matrix:
  - CI_ACTION="npm run lint"
  - CI_ACTION="npm run test:single"
after_success:
  npm run report-coverage
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d17148f8db006911346
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
